# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 02:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0002_auto_20161129_0136'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
