# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0004_navigationmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenu',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='navigationmenu',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
