# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-26 13:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0005_auto_20161226_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenu',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='auth_module.NavigationMenu'),
        ),
    ]
