# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-27 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_module', '0007_auto_20161226_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationmenu',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
