# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 03:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino_finder', '0004_auto_20161123_2051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityModel',
        ),
        migrations.RemoveField(
            model_name='doctorbiomodel',
            name='degree_ids',
        ),
        migrations.RemoveField(
            model_name='doctorbiomodel',
            name='designation_ids',
        ),
        migrations.RemoveField(
            model_name='doctorbiomodel',
            name='present_organization_ids',
        ),
        migrations.RemoveField(
            model_name='doctorbiomodel',
            name='specialist_ids',
        ),
        migrations.DeleteModel(
            name='DegreeModel',
        ),
        migrations.DeleteModel(
            name='DesignationModel',
        ),
        migrations.DeleteModel(
            name='DoctorBioModel',
        ),
        migrations.DeleteModel(
            name='HospitalINFModel',
        ),
        migrations.DeleteModel(
            name='SpecialistModel',
        ),
    ]
