# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DegreeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=50)),
                ('instititute_location', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DesignationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=50)),
                ('instititute_location', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='DoctorBioModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('picture', models.ImageField(upload_to='pictures', verbose_name='Picture')),
                ('telephone_no', models.IntegerField(verbose_name='Telephone No')),
                ('available_time', models.IntegerField(verbose_name='Available Time')),
                ('degree_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_module.DegreeModel', verbose_name='Degree')),
                ('designation_ids', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_module.DesignationModel', verbose_name='Designation')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Doctors',
            },
        ),
        migrations.CreateModel(
            name='HospitalINFModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SpecialistModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('institute_name', models.CharField(max_length=50)),
                ('instititute_location', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='doctorbiomodel',
            name='present_organization_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_module.HospitalINFModel', verbose_name='Present Organization'),
        ),
        migrations.AddField(
            model_name='doctorbiomodel',
            name='specialist_ids',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_module.SpecialistModel', verbose_name='Specialist'),
        ),
    ]
