# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbiomodel',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures', verbose_name='Picture'),
        ),
    ]
