# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_module', '0004_auto_20161202_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorbiomodel',
            old_name='degree_ids',
            new_name='degree',
        ),
        migrations.RenameField(
            model_name='doctorbiomodel',
            old_name='designation_ids',
            new_name='designation',
        ),
        migrations.RenameField(
            model_name='doctorbiomodel',
            old_name='present_organization_ids',
            new_name='present_organization',
        ),
        migrations.RenameField(
            model_name='doctorbiomodel',
            old_name='specialist_ids',
            new_name='specialist',
        ),
    ]
