# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_module', '0005_auto_20161202_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
