# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_module', '0007_auto_20161203_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorbiomodel',
            name='gender',
            field=models.CharField(default='male', max_length=30),
        ),
    ]
