# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-05 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_module', '0008_doctorbiomodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorbiomodel',
            name='gender',
            field=models.CharField(max_length=30),
        ),
    ]
